version: '3.8'
services:
  db:
    platform: linux/amd64
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vertretungsdings

  bot:
    platform: linux/amd64
    working_dir: /vertretungsbot
    build: 
      dockerfile: Dockerfile

  adminer:
    platform: linux/amd64 
    image: adminer
    restart: always
    ports:
      - 8080:8080