version: "3.7"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vertretungsdings
    volumes: 
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


  bot:
    working_dir: /vertretungsbot
    build: 
      context: .
      dockerfile: Dockerfile

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080