version: "3.7"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vertretungsdings
    volumes: 
      - ./postgres-testdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /vertretungsbot
    env_file:
      - .envtest

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080